git:
  depth: 5

addons:
  sonarcloud:
    organization: "sfireinc"
    token: "$SONARCLOUD_TOKEN"

stages:
  - "Build and Test"
  - "Package"

jobs:
  include:
  - stage: "Build and Test"
    language: java
    jdk: oraclejdk11
    before_script:
    - cd sample-application-backend
    script:
    - mvn clean
    - mvn verify

  - stage: "Quality Gate [Sonar Cloud]"
    language: java
    jdk: oraclejdk11
    before_script:
    - cd sample-application-backend
    script:
    - mvn test
    - mvn org.jacoco:jacoco-maven-plugin:prepare-agent 
    - mvn sonar:sonar -Dsonar.projectKey=SfireInc_sample-application-students

  - stage: "Build and Test"
    language: node_js
    node_js: "12.20"
    before_script:
    - cd sample-application-frontend

  - stage: "Build Push BackEnd docker image"
    before_script:
    - cd sample-application-backend
    script:
    - docker build -t sfireinc/devops:backend .
    - docker login -p $DOCKER_PASSWORD -u $DOCKER_USER
    - docker push sfireinc/devops:backend
    
  - stage: "Build Push FrontEnd docker image"
    before_script:
    - cd sample-application-frontend
    script:
    - docker build -t sfireinc/devops:frontend .
    - docker login -p $DOCKER_PASSWORD -u $DOCKER_USER
    - docker push sfireinc/devops:frontend

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.npm"

services:
- docker